### ISSUE TITLE
The Python 3 Laubwerk SDK is not yet available

### ISSUE THREAD

**Issue by c1symeon** [Thicket-Blender/thicket#9] opened 2020-02-18 05:31 UTC
I contacted I Laubwerk. They are not willing to distribute the SDK. Without it your add-on is not usable.

**Comment by dvhart** [comment] 2020-02-18 05:41
I'm sorry to hear they weren't willing to share the development SDK . I have been in touch with them this last week, and they are working toward the general release of the python3 SDK. I'll receive a beta of that for testing. Unfortunately, I don't have an ETA on that release, and it's beyond my control. I will update the README so others don't lose time asking for the SDK until they release it (at which point it will come with every plant kit). I hope you'll watch the project and try again when the SDK is available. I'll leave this issue open to track that progress.

**Comment by Spirou4D** [comment] 2020-02-19 12:25
Yes I have the same problem with _lbwbl.pyd's python 3.7 : don't exist!

**Comment by dvhart** [comment] 2020-03-24 03:12
@c1symeon @Spirou4D I've invited you to a repository named "thicket" (https://github.com/dvhart/thicket) which is a temporarily private repository where I've continued this development of this Addon. I plan to move it to public next week. As the first two people to attempt to try the Addon, I wanted to invite you to try again with a Laubwerk Plant Kit versions 1.0.32 or later which now contains the Python 3 SDK. I'm using this on both Mac and Windows with Blender 2.82. If you are will to spend the time, I'd be grateful for a couple of interested users giving it a spin and sharing feedback with me.

**Comment by dvhart** [comment] 2020-04-05 21:42
As of now, the plant kits include the necessary Python support to work with Blender 2.80+ and Thicket. I have to apologize to everyone for the confusion around access to the development version of the SDK. I misunderstood what was available and caused both you and the good folks at Laubwerk some problems. Thank you for the understanding a patience.

**Comment by modosgit** [comment] 2020-04-09 12:10
I try to enable in blender 2.82a but the Laubwerk install path is always red.
LaubwerkPlantsKitFreebie_1.0.32 - thicket-0_2_0-alpha

**Comment by dvhart** [comment] 2020-04-09 13:38
Hi @modosgit , thanks for testing and reporting the issue. I suspect this is a new issue (related to the change to the way 2.82 handles internal paths). To help me reproduce:

What operating system are you using? Windows or Mac?
Which Laubwerk Plant Kit did you install? Plant Kit Freebie?
Where is the Laubwerk Path on your computer? C:\Program Files (x86)\Laubwerk?
What is displayed in the Laubwerk Path box when it is showing as red? Is it empty? does it look something like "..\..\..\..\Program Files(x86)\Laubwerk?

If the latter, please try selecting the same path again - I've found on Windows that choosing it again will force the update to use the C:\Program Files (x86)\Laubwerk path (which is a bug and needs fixing).

**Comment by modosgit** [comment] 2020-04-10 19:49
Hi dvhart,
windows system
Laubwerk Path C:\Program Files\Laubwerk
in red i have C:\Program Files\Laubwerk
Thanks for your work

**Comment by dvhart** [comment] 2020-04-10 20:04
@modosgit can you check which folders exist inside C:\Program Files\Laubwerk? There should be "Plants" and "Python". If Python is not there, can you try installing again, choose "custom" and be sure to check the "Python Extension" component in the installer options?

**Comment by modosgit** [comment] 2020-04-11 09:56
yes inside C:\Program Files\Laubwerk there is a Python folden.
inside Python there is another laubwerk folder with python file inside

**Comment by dvhart** [comment] 2020-04-11 18:42
Thanks @modosgit , I think I found an error in the absolute path conversion of the Laubwerk Install path in the Thicket preferences code which affected Windows platforms. I've created a fix that works for me with Windows 10 and a fresh install of Blender 2.82a. Can you please try the thicket-v0_2_0-alpha2 release (https://github.com/Thicket-Blender/thicket/releases/tag/v0_2_0-alpha2). Please disable and remove any existing Thicket installations.

If this doesn't work, can you please share your terminal log output as well? You can get the Blender terminal log in Windows by starting Blender from the Terminal using a command like the following:

C:\Users\modosgit> "C:\Program Files\Blender Foundation\Blender 2.82\blender.exe"

**Comment by modosgit** [comment] 2020-04-12 13:34
Thanks, the problem was i have plants in a different folder.
Sorry

**Comment by dvhart** [comment] 2020-04-12 15:02
@modosgit thanks for following up - much appreciated. I'm going to close this issue out then. However, if you feel that Thicket assuming the Plants and Python folders are in the standard location is an unnecessary limitation, we're happy to consider adding a custom paths section to the settings. I was not aware that Laubwerk users might need to move these directories. If you feel this should be addressed, would you please open a new issue and describe why it's necessary (e.g. do you need Plants in a different directory in order to work with another piece of software? Thicket shouldn't force you to choose between one or the other working). Thanks!

**Closed by dvhart** 2020-04-12 15:02 UTC
Labels: bug
