### ISSUE TITLE
Laubwerk Python Extension 1.0.34 not supported

### ISSUE THREAD

**Issue by tdapper** [Thicket-Blender/thicket#27] opened 2020-10-15 17:06 UTC
The material system has undergone substantial changes with the Python Extension 1.0.24. Some material properties have been renamed (e.g. `diffuse_color` to `base_color` and a bunch have been added (e.g. `specular_roughness_texture` or `sheen`).

**Comment by dvhart** [comment] 2020-10-15 18:20
Thanks @tdapper , marking as a duplicate of #26 . Will include the above comment there, and address the issue in that ticket.

**Closed by dvhart** 2020-10-15 18:20 UTC
Labels: bug, duplicate
